name: device_finder
description: A package that helps with device specific actions
version: 1.0.0
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  io: ^1.0.0
  meta: ^1.3.0
  # path_provider: ^2.0.5
  archive: ^3.1.2

dev_dependencies:
  test: